import type { Evidence, EvidenceContext, SourceItem, Study } from "./api";

export const demoStudies: Study[] = [
  {
    id: "demo-helphub",
    title: "HelpHub AI Assist",
    decisionQuestion: "下一季度应该优先做 AI 自动回复、自动分类，还是高风险工单升级？",
    status: "active",
    updatedAt: "2026-07-15T03:28:00.000Z",
    sourceCount: 6,
    evidenceCount: 24,
  },
  {
    id: "demo-onboarding",
    title: "Enterprise onboarding",
    decisionQuestion: "如何把企业客户的首次价值实现时间从 21 天缩短到 7 天？",
    status: "draft",
    updatedAt: "2026-07-13T09:12:00.000Z",
    sourceCount: 4,
    evidenceCount: 11,
  },
  {
    id: "demo-retention",
    title: "Admin retention",
    decisionQuestion: "哪些管理端工作流最能预测 90 天续费？",
    status: "archived",
    updatedAt: "2026-07-02T07:40:00.000Z",
    sourceCount: 8,
    evidenceCount: 37,
  },
];

export const demoSources: Record<string, SourceItem[]> = {
  "demo-helphub": [
    {
      id: "src-interviews",
      name: "support_lead_interviews.pdf",
      type: "PDF · 18 pages",
      status: "ready",
      progress: 100,
      updatedAt: "11:41",
    },
    {
      id: "src-tickets",
      name: "support_tickets_q2.csv",
      type: "CSV · 3,248 rows",
      status: "ready",
      progress: 100,
      updatedAt: "11:39",
    },
    {
      id: "src-competitors",
      name: "competitor_pages.zip",
      type: "Web snapshots · 12",
      status: "processing",
      progress: 72,
      updatedAt: "11:43",
    },
  ],
  "demo-onboarding": [],
  "demo-retention": [],
};

export const demoEvidence: Evidence[] = [
  {
    id: "ev-risk-escalation",
    revisionId: "evr_01JZ7X4M8K",
    studyId: "demo-helphub",
    kind: "pain",
    title: "高风险工单被发现得太晚",
    quote: "最怕的不是回复慢，是一条要流失的工单静静躺了四个小时，我们根本不知道。",
    observation: "6 位支持负责人中有 5 位主动提到：高风险工单缺少即时识别与升级机制。",
    interpretation: "比起生成回复，团队更愿意先为“可靠地发现风险”付费，因为它直接影响客户流失和 SLA。",
    sourceName: "support_lead_interviews.pdf",
    sourceId: "src-interviews",
    sourceRevisionId: "sr_01JZ7WZE3P",
    sourceType: "Interview transcript",
    locatorLabel: "p. 14 · lines 8–12 · Speaker S05",
    reviewStatus: "approved",
    confidence: 0.93,
    relationship: "supports",
    tags: ["retention risk", "escalation", "SLA"],
    syntheticDemo: false,
    createdAt: "2026-07-15T03:42:03.000Z",
  },
  {
    id: "ev-auto-reply-frequency",
    revisionId: "evr_01JZ7X7H3D",
    studyId: "demo-helphub",
    kind: "behavior",
    title: "自动回复被频繁提及，但修订率很高",
    quote: "我们试过生成式回复，十条里大概七条还是要大改，省下来的时间没有想象中多。",
    observation: "自动回复是访谈中提及次数最高的需求，但现有试用者平均重写 68% 的生成内容。",
    interpretation: "需求声量并不等于价值；若不能显著降低修订率，自动回复的采用率会被高估。",
    sourceName: "support_lead_interviews.pdf",
    sourceId: "src-interviews",
    sourceRevisionId: "sr_01JZ7WZE3P",
    sourceType: "Interview transcript",
    locatorLabel: "p. 7 · lines 19–24 · Speaker S02",
    reviewStatus: "reviewed",
    confidence: 0.86,
    relationship: "challenges",
    tags: ["auto reply", "adoption", "editing"],
    syntheticDemo: false,
    createdAt: "2026-07-15T03:42:18.000Z",
  },
  {
    id: "ev-ticket-volume",
    revisionId: "evr_01JZ7XB2TY",
    studyId: "demo-helphub",
    kind: "signal",
    title: "升级类工单只占 8%，却消耗 31% 处理时长",
    quote: "ticket_type=escalation · 261 / 3,248 tickets · median_handle_time=46m",
    observation: "升级类工单数量较少，但中位处理时长是普通工单的 4.2 倍。",
    interpretation: "这是一个低频高成本队列，适合用风险识别和路由降低尾部损失。",
    sourceName: "support_tickets_q2.csv",
    sourceId: "src-tickets",
    sourceRevisionId: "sr_01JZ7X0C2N",
    sourceType: "CSV dataset",
    locatorLabel: "rows 882–1142 · ticket_type=escalation · SHA 6f4…c19",
    reviewStatus: "pending",
    confidence: 0.89,
    relationship: "supports",
    tags: ["volume", "handle time", "operations"],
    syntheticDemo: false,
    createdAt: "2026-07-15T03:42:31.000Z",
  },
  {
    id: "ev-classification-baseline",
    revisionId: "evr_01JZ7XDM6R",
    studyId: "demo-helphub",
    kind: "counterevidence",
    title: "规则分类已覆盖多数常规路由",
    quote: "现有规则对 billing、bug、how-to 三类工单的准确率已经稳定在 91%。",
    observation: "常规分类已有可靠规则基线，错误主要集中在跨意图和高风险隐性表达。",
    interpretation: "做通用自动分类的边际收益有限，应把模型能力聚焦于规则难以覆盖的风险识别。",
    sourceName: "routing_metrics_q2.csv",
    sourceId: "src-routing",
    sourceRevisionId: "sr_01JZ7X24QK",
    sourceType: "Metrics export",
    locatorLabel: "query q2_routing_accuracy_v4 · 2026-04-01—06-30",
    reviewStatus: "approved",
    confidence: 0.96,
    relationship: "challenges",
    tags: ["baseline", "classification", "accuracy"],
    syntheticDemo: false,
    createdAt: "2026-07-15T03:43:01.000Z",
  },
  {
    id: "ev-security-constraint",
    revisionId: "evr_01JZ7XG7B4",
    studyId: "demo-helphub",
    kind: "constraint",
    title: "企业客户要求可解释的升级原因",
    quote: "如果系统把工单升级给法务，我们必须知道触发了哪条信号，不能只给一个风险分。",
    observation: "受访的 3 家企业客户均要求风险判断保留触发片段和规则/模型版本。",
    interpretation: "风险能力的最小可用形态必须包含可追溯理由、置信度和人工覆核入口。",
    sourceName: "enterprise_requirements.docx",
    sourceId: "src-requirements",
    sourceRevisionId: "sr_01JZ7X35CA",
    sourceType: "Sales requirements",
    locatorLabel: "§ 3.2 · Requirement ENT-17 · revision 4",
    reviewStatus: "reviewed",
    confidence: 0.9,
    relationship: "supports",
    tags: ["explainability", "enterprise", "governance"],
    syntheticDemo: false,
    createdAt: "2026-07-15T03:43:25.000Z",
  },
];

export const demoContexts: Record<string, EvidenceContext> = {
  "ev-risk-escalation": {
    evidenceId: "ev-risk-escalation",
    sourceName: "support_lead_interviews.pdf",
    locatorLabel: "p. 14 · lines 8–12 · Speaker S05",
    before:
      "Interviewer: 过去一个季度，支持团队最希望改善的环节是什么？\nS05: 回复效率当然重要，我们每天都有大量重复问题。",
    highlight:
      "最怕的不是回复慢，是一条要流失的工单静静躺了四个小时，我们根本不知道。等客户成功经理来问时，已经晚了。",
    after:
      "S05: 如果系统能把这种工单提前标出来，哪怕回复还是人工写，我们也能先救火。\nInterviewer: 什么信号会让你相信这个判断？",
  },
  "ev-auto-reply-frequency": {
    evidenceId: "ev-auto-reply-frequency",
    sourceName: "support_lead_interviews.pdf",
    locatorLabel: "p. 7 · lines 19–24 · Speaker S02",
    before: "S02: 我们在另一个工具里开过三周的 AI 回复试用，大家一开始都很兴奋。",
    highlight: "我们试过生成式回复，十条里大概七条还是要大改，省下来的时间没有想象中多。",
    after: "S02: 如果它先帮我判断客户是不是在生气，可能反而更实用。",
  },
  "ev-ticket-volume": {
    evidenceId: "ev-ticket-volume",
    sourceName: "support_tickets_q2.csv",
    locatorLabel: "rows 882–1142 · ticket_type=escalation · SHA 6f4…c19",
    before: "Dataset filter: created_at ≥ 2026-04-01, created_at < 2026-07-01\nGroup: ticket_type",
    highlight: "escalation | 261 tickets | median_handle_time 46m | p90_first_response 3h 12m",
    after: "all_other | 2,987 tickets | median_handle_time 11m | p90_first_response 48m",
  },
  "ev-classification-baseline": {
    evidenceId: "ev-classification-baseline",
    sourceName: "routing_metrics_q2.csv",
    locatorLabel: "query q2_routing_accuracy_v4 · 2026-04-01—06-30",
    before: "billing accuracy: 0.93\nbug accuracy: 0.90\nhow-to accuracy: 0.92",
    highlight: "weighted average accuracy: 0.91 | cross-intent accuracy: 0.64 | implicit-risk recall: 0.38",
    after: "Rule set: routing_rules_v12\nEvaluation set: 1,204 human-labeled tickets",
  },
  "ev-security-constraint": {
    evidenceId: "ev-security-constraint",
    sourceName: "enterprise_requirements.docx",
    locatorLabel: "§ 3.2 · Requirement ENT-17 · revision 4",
    before: "ENT-16: Administrators can configure which queues are eligible for automated escalation.",
    highlight: "ENT-17: Every automated escalation must expose the triggering passage, policy, confidence and model version to an authorized reviewer.",
    after: "ENT-18: A reviewer can override the escalation and record a reason without modifying the original event.",
  },
};

export const demoAgentEvents = [
  { id: "run-1", label: "Source parser", detail: "18 pages · 142 segments", status: "complete", time: "11:41:52" },
  { id: "run-2", label: "Evidence extractor", detail: "24 candidates · schema valid", status: "complete", time: "11:42:03" },
  { id: "run-3", label: "Hybrid retrieval", detail: "top-k 18 · reranked to 7", status: "complete", time: "11:42:08" },
  { id: "run-4", label: "Skeptic agent", detail: "Checking counterevidence", status: "running", time: "11:42:11" },
  { id: "run-5", label: "Human review", detail: "Approval required", status: "pending", time: "—" },
] as const;
