from enum import StrEnum


class ClaimIntegrityBlocker(StrEnum):
    """Stable blocker codes shared by deterministic policy checks and APIs."""

    NO_CONFIRMED_SUPPORT = "NO_CONFIRMED_SUPPORT"
    FORMAL_RELATION_NOT_CONFIRMED = "FORMAL_RELATION_NOT_CONFIRMED"
    EVIDENCE_REVIEW_NOT_ACCEPTED = "EVIDENCE_REVIEW_NOT_ACCEPTED"
    SYNTHETIC_EVIDENCE = "SYNTHETIC_EVIDENCE"
    CROSS_STUDY_EVIDENCE = "CROSS_STUDY_EVIDENCE"
    EVIDENCE_REVISION_MISMATCH = "EVIDENCE_REVISION_MISMATCH"
    NOT_CURRENT_EVIDENCE_REVISION = "NOT_CURRENT_EVIDENCE_REVISION"
    CITATION_INTEGRITY_FAILED = "CITATION_INTEGRITY_FAILED"
    LOCATOR_REPLAY_FAILED = "LOCATOR_REPLAY_FAILED"
    SOURCE_HASH_MISMATCH = "SOURCE_HASH_MISMATCH"
    COUNTEREVIDENCE_NOT_RUN = "COUNTEREVIDENCE_NOT_RUN"


CLAIM_INTEGRITY_BLOCKER_ORDER: tuple[ClaimIntegrityBlocker, ...] = tuple(ClaimIntegrityBlocker)
